### ISSUE TITLE
Temperature number shown should be in Celsius

### ISSUE THREAD

**Issue by Alejandro-HUB** [Alejandro-HUB/PCUMS#13]
The temperature on Form1 is not too accurate. If that is the closest we can get then it's ok but the difference is there.
Most monitoring Software use Celsius vs Fahrenheit we could also offer an option to switch between both.

Good job on adding temperature controls to our App!

### **Temperature on PCUMS:** 
![image](https://user-images.githubusercontent.com/58063303/156282980-0a5d1208-8252-462f-ae4f-d9f2607fc9a5.png)
101 F = 37 c

### **Actual temperature:**
![image](https://user-images.githubusercontent.com/58063303/156283176-aef1fd7b-1821-46eb-940e-82d027f92a7f.png)
57 c = 134 Farenheit  

### **Difference:** 
31 F = 18 C.

**Comment by Oozaru71** [comment]
The reason it might not be accurate is that you might have a different amount of cores on your CPU than I do, right now it takes the sum of all the cores and divides by the number of cores. I will figure out how to get the number of cores dynamically so it can be accurate for all systems.
